--LIMPAR OS DADOS DA BASE
TRUNCATE TABLE TB_Produto RESTART IDENTITY CASCADE;

--Insersão de produtos na base
INSERT INTO TB_PRODUTO (Nome_Produto,Descricao_Produto, Preco_Produto, Status_Produto) VALUES
('Hamburguer de Javali', 'Pão, carne, salada', 40.0, true),
('Pizza de Pepperoni', 'Massa, pepperoni, queijo', 55.0, true),
('Sushi Especial', 'Arroz, salmão, nori', 32.0, true),
('Taco Mexicano', 'Tortilla, carne moída, alface', 22.0, true),
('Camarão Empanado', 'Camarão, farinha, temperos', 48.0, true),
('Bife Ancho', 'Carne bovina, sal grosso', 72.0, true),
('Risoto de Cogumelos', 'Arroz arbóreo, cogumelos, creme', 45.0, true),
('Lasanha Bolonhesa', 'Massa, carne, queijo', 38.0, true),
('Salada Caesar', 'Alface, frango, croutons', 28.0, true),
('Wrap de Frango', 'Tortilla, frango, legumes', 26.0, true),
('Pastel de Queijo', 'Massa, queijo', 9.0, true),
('Coxinha Tradicional', 'Frango, massa, farinha', 8.0, true),
('Espaguete à Carbonara', 'Massa, ovos, pancetta', 44.0, true),
('Frango Grelhado', 'Peito de frango, temperos', 30.0, true),
('Carne de Panela', 'Acém, legumes', 36.0, true),
('Picanha Grelhada', 'Picanha, sal grosso', 85.0, true),
('Tilápia Frita', 'Peixe, farinha, temperos', 33.0, true),
('Moqueca Baiana', 'Peixe, leite de coco, dendê', 60.0, true),
('Tortinha de Limão', 'Massa, limão, creme', 14.0, true),
('Brownie com Sorvete', 'Chocolate, sorvete', 20.0, true),
('Batata Rústica', 'Batata, páprica, sal', 18.0, true),
('Panqueca Recheada', 'Massa, carne, molho', 24.0, true),
('Esfiha de Carne', 'Massa, carne temperada', 7.0, true),
('Churrasco Misto', 'Carne, frango, linguiça', 70.0, true),
('Feijoada Completa', 'Feijão, carnes, farofa', 42.0, true),
('Omelete Especial', 'Ovos, queijo, presunto', 19.0, true),
('Caldo de Mandioca', 'Mandioca, carne seca', 16.0, true),
('Bolo de Cenoura', 'Cenoura, chocolate', 12.0, true),
('Panqueca Doce', 'Massa, doce de leite', 17.0, true),
('Hot Dog Tradicional', 'Pão, salsicha, molho', 15.0, true),
('Kibe Frito', 'Trigo, carne', 8.0, true),
('Croissant Recheado', 'Massa folhada, queijo', 11.0, true),
('Torta de Frango', 'Frango, massa, milho', 22.0, true),
('Arroz Carreteiro', 'Arroz, carne seca, temperos', 27.0, true),
('Strogonoff de Frango', 'Frango, creme, molho', 34.0, true),
('Strogonoff de Carne', 'Carne, creme, molho', 39.0, true),
('Yakissoba Tradicional', 'Macarrão, legumes, carne', 31.0, true),
('Hambúrguer Vegano', 'Pão, hambúrguer vegetal, salada', 37.0, true),
('Quiche de Alho-Poró', 'Massa, alho-poró, creme', 29.0, true),
('Filé de Merluza', 'Peixe, limão, temperos', 28.0, true),
('Pão de Alho Recheado', 'Pão, queijo, alho', 14.0, true),
('Brigadeiro Gourmet', 'Chocolate, creme', 6.0, true),
('Tapioca Recheada', 'Goma, queijo', 10.0, true),
('Açaí na Tigela', 'Açaí, granola, banana', 18.0, true),
('Milkshake de Morango', 'Leite, sorvete, morango', 22.0, true),
('Suco Detox', 'Couve, limão, maçã', 12.0, true),
('Café Expresso', 'Café', 7.0, true),
('Chá Gelado', 'Chá, limão', 9.0, true);
