
--Insersão de produtos na base
INSERT INTO TB_Produto (nomeproduto, descricaoproduto, precoproduto, ativo) VALUES

('Pizza de Pepperoni', 'Massa, molho de tomate, pepperoni, mussarela', 55.0, true),
('Pizza de Calabresa', 'Massa, molho de tomate, calabresa, cebola, mussarela', 48.0, true),
('Pizza Margherita', 'Massa, molho de tomate, mussarela de búfala, manjericão', 52.0, true),
('Pizza Quatro Queijos', 'Massa, mussarela, parmesão, provolone, gorgonzola', 58.0, true),
('Pizza Frango com Catupiry', 'Massa, frango desfiado, catupiry original, milho', 54.0, true),
('Pizza de Coração de Galinha', 'Massa, mussarela, coração acebolado, batata palha', 62.0, true),
('Pizza de Estrogonofe de Carne', 'Massa, estrogonofe de filé, mussarela, batata palha', 65.0, true),
('Pizza de Carne de Sol', 'Massa, carne de sol, queijo coalho, manteiga de garrafa', 60.0, true),
('Pizza Vegana de Cogumelos', 'Massa integral, queijo de castanha, shimeji e paris', 59.0, true),
('Pizza de Picanha ao Alho', 'Massa, tiras de picanha, mussarela, alho crocante', 78.0, true),
('Pizza de Camarão com Cream Cheese', 'Massa, camarões, cream cheese, alho-poró', 82.0, true),
('Pizza de Bacon com Mel', 'Massa, mussarela, bacon crocante e mel silvestre', 58.0, true),
('Pizza Carbonara', 'Massa, creme de leite, ovos, bacon, parmesão', 58.0, true),
('Pizza Burger', 'Massa, mini hambúrgueres, cheddar, picles', 66.0, true),
('Pizza de Lombo com Damasco', 'Massa, lombo defumado, queijo brie, damasco', 68.0, true),
('Pizza de Jacaré', 'Massa, carne de jacaré temperada, cream cheese e ervas', 110.0, true),
('Pizza de Kimchi', 'Massa, kimchi fermentado, carne de porco e gergelim', 65.0, true),
('Pizza de Nachos', 'Massa, carne moída picante, cheddar e Doritos', 57.0, true),
('Pizza de Sushi', 'Massa crocante, salmão, cream cheese, cebolinha e tarê', 85.0, true),
('Pizza de Costela com Barbecue', 'Massa, costela desfiada e molho barbecue', 64.0, true),
('Pizza Doce Romeu e Julieta', 'Massa, mussarela, goiabada cascão, queijo minas', 45.0, true),
('Pizza Doce de Nutella', 'Massa, creme de avelã Nutella e morangos frescos', 55.0, true),
('Pizza Doce de Banoffee', 'Massa, doce de leite, banana e canela', 48.0, true),
('Pizza Doce de Chocolate Branco', 'Massa, chocolate branco e raspas de limão', 50.0, true),
('Pizza Doce de M&Ms', 'Massa, ganache de chocolate e confeitos M&Ms', 52.0, true),
('Calzone de Frango', 'Massa fechada, frango, catupiry e milho', 48.0, true),
('Calzone de Chocolate', 'Massa fechada, chocolate ao leite e granulado', 44.0, true),
('Pão de Alho Especial', 'Pão italiano, creme de alho e mussarela', 18.0, true),
('Focaccia de Alecrim', 'Massa de pizza, alecrim, azeite e sal grosso', 22.0, true),
('Crostini de Parmesão', 'Massa fina crocante, azeite e parmesão', 15.0, true),
('Coca-Cola Lata', 'Refrigerante Coca-Cola 350ml', 7.5, true),
('Guaraná Antarctica 2L', 'Refrigerante Guaraná Antarctica garrafa 2 litros', 15.0, true),
('Cerveja Heineken', 'Cerveja Heineken Long Neck 330ml', 12.0, true),
('Cerveja Colorado IPA', 'Cerveja Artesanal Colorado Indica 600ml', 26.0, true),
('Suco Del Valle Uva', 'Suco de Uva Del Valle lata 290ml', 8.0, true),
('Suco Natural de Laranja', 'Suco Prats 100% natural 400ml', 12.0, true),
('Água Crystal sem Gás', 'Água Mineral Crystal 500ml', 4.5, true),
('Água Crystal com Gás', 'Água Mineral Crystal com Gás 500ml', 5.5, true),
('Vinho Casillero del Diablo', 'Taça de vinho tinto Cabernet Sauvignon', 25.0, true),
('Lipton Ice Tea', 'Chá gelado Lipton sabor Pêssego 340ml', 9.0, true);